# Generated by Django 5.2.5 on 2025-11-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionrecurrente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='cuenta_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ahorro', to='gestion.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_destino', to='gestion.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_origen', to='gestion.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA', 'Transferencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccionrecurrente',
            name='cuenta_relacionada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccionrecurrente',
            name='frecuencia',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccionrecurrente',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA', 'Transferencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
